# Generated by Django 4.2.6 on 2023-11-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_person_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requested_users_status',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
