# Generated by Django 4.2.6 on 2023-11-10 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_alter_requested_users_status_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requested_users_status',
            name='user',
        ),
        migrations.AddField(
            model_name='requested_users_status',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requested_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
